import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import ThemeProvider from "./providers/theme-provider";
import Footer from "@/components/footer";
import AppProvider from "./providers/app-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AppProvider>
					<ThemeProvider>
						<div className="flex flex-col justify-between min-h-screen">
							<Header />
							{/* <Link href="/categories">Categorie</Link> */}
							<div className="flex-grow">{children}</div>

							<Footer />
						</div>
					</ThemeProvider>
				</AppProvider>
			</body>
		</html>
	);
}
